### ISSUE TITLE
HarmonicModel and HarmonicMask unit tests fail

### ISSUE THREAD

**Issue by dbogdanov** [jjaner/essentia-musicbricks#7]
On Ubuntu: 

```
======================================================================
FAIL: testRegression (synthesis.test_harmonicmodel_streaming.TestHarmonicModel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dbogdanov/essentia/test/src/unittest/synthesis/test_harmonicmodel_streaming.py", line 254, in testRegression
    self.assertAlmostEqualVectorFixedPrecision(outsignal[halfwin:-halfwin], signal[halfwin:-halfwin], self.precisionDigits)
  File "/home/dbogdanov/essentia/test/src/unittest/essentia_test.py", line 102, in assertAlmostEqualVectorFixedPrecision
    self.assertAlmostEqualFixedPrecision(val1, val2, digits)
  File "/home/dbogdanov/essentia/test/src/unittest/essentia_test.py", line 88, in assertAlmostEqualFixedPrecision
    BaseTestCase.assertAlmostEqual(self, found, expected, digits)
AssertionError: -334.58459 != -0.16698757 within 1 places

======================================================================
FAIL: testRegression (synthesis.test_harmonicmask_streaming.TestHarmonicMask)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dbogdanov/essentia/test/src/unittest/synthesis/test_harmonicmask_streaming.py", line 137, in testRegression
    self.assertAlmostEqualVectorFixedPrecision(outsignal[halfwin:-halfwin], signal[halfwin:-halfwin], self.precisionDigits)
  File "/home/dbogdanov/essentia/test/src/unittest/essentia_test.py", line 102, in assertAlmostEqualVectorFixedPrecision
    self.assertAlmostEqualFixedPrecision(val1, val2, digits)
  File "/home/dbogdanov/essentia/test/src/unittest/essentia_test.py", line 88, in assertAlmostEqualFixedPrecision
    BaseTestCase.assertAlmostEqual(self, found, expected, digits)
AssertionError: 653.7345 != 0.31479892 within 1 places
```

**Comment by jjaner** [comment]
There was a parameter missing in this unit tests after a refactoring of the OverlapAdd algorithm.
It should be working fine now. Please git pull!
